# Hackly repo scan report

Authorized security assessment — machine-readable Markdown for AI / tooling.

## Scan metadata

| Field | Value |
| --- | --- |
| Repository | {!! $scan->repository?->full_name ?? '—' !!} |
| Scan ID | `{{ $scan->id }}` |
| Profile | `{{ $scan->profile->value }}` |
| Status | `{{ $scan->status->value }}` |
| Commit | `{{ $scan->commit_sha ?? '—' }}` |
| Started | {{ optional($scan->started_at ?? $scan->created_at)->toIso8601String() ?? '—' }} |
| Finished | {{ optional($scan->finished_at)->toIso8601String() ?? '—' }} |
| Requested by | {{ $scan->requester?->email ?? '—' }} |
| Findings | {{ $findings->count() }} |
| Generated at | {{ $generatedAt->toIso8601String() }} |

## Severity overview

| Severity | Count |
| --- | --- |
| HIGH | {{ $summary['high'] }} |
| MEDIUM | {{ $summary['medium'] }} |
| LOW | {{ $summary['low'] }} |

## Scan tasks

@forelse ($scan->tasks as $task)
- **{{ $task->type?->label() ?? $task->type?->value ?? '—' }}** — `{{ $task->status->value }}`
  - started: {{ optional($task->started_at)->toIso8601String() ?? '—' }}
  - finished: {{ optional($task->finished_at)->toIso8601String() ?? '—' }}
@if (filled($task->error_message))
  - error: {!! $task->error_message !!}
@endif
@empty
_No tasks recorded._
@endforelse

## Findings

@forelse ($findings as $index => $finding)
### {{ $index + 1 }}. {!! $finding->title !!}

- **Severity:** `{{ $finding->severity->value }}` ({{ $finding->severity->label() }})
- **Source:** `{{ $finding->source }}`
- **Category:** `{{ $finding->category ?? '—' }}`
- **CVE:** `{{ $finding->cve ?? '—' }}`
- **Reachability:** `{{ $finding->reachability?->value ?? '—' }}`
- **Status:** `{{ $finding->status->value }}`
- **Fingerprint:** `{{ $finding->fingerprint }}`

@if (filled($finding->description))
#### Description

{!! $finding->description !!}

@endif
@php($evidenceLines = $finding->evidenceDetailLines())
@if ($evidenceLines !== [])
#### Detail / evidence

```
{!! implode("\n", $evidenceLines) !!}
```

@endif
@if (! empty($finding->evidence) && is_array($finding->evidence))
#### Evidence JSON

```json
{!! json_encode($finding->evidence, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_INVALID_UTF8_SUBSTITUTE) !!}
```

@endif
---

@empty
_No findings were reported for this scan._
@endforelse

_Generated by Hackly · Authorized assessment only_
